### ISSUE TITLE
Nor Ptam or Cameracalibrator show image from camera

### ISSUE THREAD

**Issue by dielopez** [ethz-asl/ethzasl_ptam#3]
Hello,

I am very interested in trying out your Ptam package. It looks a very promising tool. However I am facing a problem you might be able to help. My issue is that whilst I am capable of seeing properly the image of the camera using the standard "rosrun image_view image_view image:=camera/image_raw", I am not capable of seeing anything when running "roslaunch ptam cameracalibrator.launch" ( the node runs properly, and I get some green points but nothing else). Do you have an explanation why it happens?

Thanks in advance, 

Diego

**Comment by ziyangli** [comment]
Hello, I am using a Nvidia laptop but I can not get the GUI either.

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[ INFO] [1429273119.545545084]: starting CameraCalibrator with node name /cameracalibrator
  Welcome to CameraCalibrator 
  -------------------------------------- 
  Parallel tracking and mapping for Small AR workspaces
  Copyright (C) Isis Innovation Limited 2008 
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[New Thread 0x7fffe9d14700 (LWP 7755)]
[New Thread 0x7fffe9513700 (LWP 7756)]
[New Thread 0x7fffe8d12700 (LWP 7757)]
[New Thread 0x7fffe3fff700 (LWP 7762)]
Gui is on
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]

```

**Comment by stephanweiss** [comment]
are you using gbd? then it might be related to this:
https://github.com/ros/ros_comm/issues/223

There are a couple of hits in google with respect to this issue under ROS. Was any result useful for your case?

Best,
Stephan


________________________________

**Comment by ziyangli** [comment]
Well I remove launch-prefix but there is still no GUI, so I guess it is other issue.

**Comment by ziyangli** [comment]
```
[ INFO] [1429346288.408952217]: starting CameraCalibrator with node name /cameracalibrator
  Welcome to CameraCalibrator 
  -------------------------------------- 
  Parallel tracking and mapping for Small AR workspaces
  Copyright (C) Isis Innovation Limited 2008 
Gui is on
```

This is what I get if I removed `launch-prefix`. Although it says `Gui is on`, the program just hang there and nothing happens.

**Comment by ziyangli** [comment]
It works now. All I change is that I remap the image topic correctly.
