### ISSUE TITLE
Cannot install ethzasl_ptam package

### ISSUE THREAD

**Issue by ldkge** [ethz-asl/ethzasl_ptam#53]
I'm following the instructions at the package page at ros.org

    # Fetch ethzasl_ptam stack
    git clone git://github.com/ethz-asl/ethzasl_ptam.git ethzasl_ptam

    # Update ROS_PACKAGE_PATH (if necessary)
    export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:`pwd`/ethzasl_ptam

    # Install ROS standalone tools, if not done already
    sudo apt-get install python-rosinstall python-rosdep

    # Install system dependencies:
    rosdep install ptam

and on the last step (rosdep install ptam) I get

    ERROR: the following packages/stacks could not have their rosdep keys resolved
    to system dependencies:
    ptam: Cannot locate rosdep definition for [ptam_com]

Any ideas what's going wrong?

**Comment by simonlynen** [comment]
Please take a look at: https://github.com/ethz-asl/ethzasl_ptam/issues/50
