### ISSUE TITLE
initialization failure for PTAM

### ISSUE THREAD

**Issue by Ziyou1987** [ethz-asl/ethzasl_ptam#54]
Hi, guys

I run the PTAM following this tutorial because my laptop does not have a Nvidia graphic card:
http://wiki.ros.org/ethzasl_ptam/Tutorials/remote_ptam

I got:
process[ptam-1]: started with pid [5581]
[ INFO] [1422319852.242389196]: starting ptam with node name /ptam
  Welcome to PTAM 
  --------------- 
  Parallel tracking and mapping for Small AR workspaces
  Copyright (C) Isis Innovation Limited 2008 
Gui is off                     

Then I run the remote_ptam. When I first pressed the space key, I can see feature tracks when I moved the camera but when I pressed the space key again, the PTAM node died immediately:
[ptam-1] process has died [pid 5581, exit code -4, cmd /home/liping/catkin_ws/devel/lib/ptam/ptam image:=/gray/image_raw pose:=pose __name:=ptam __log:=/home/liping/.ros/log/88182626-a5be-11e4-87f3-40e2301b88e0/ptam-1.log].
log file: /home/liping/.ros/log/88182626-a5be-11e4-87f3-40e2301b88e0/ptam-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete

I tried many times with large baseline between the first key frames. Any idea why this happens? 
Thank you. 

BTW, this link: https://github.com/ethz-asl/ethzasl_ptam/issues/6 did not help me solve my problem.

**Comment by Ziyou1987** [comment]
I am now using Ubuntu 14.04 and ROS indigo on my ASUS laptop. The above problem is gone. But, during initialization, I always got the warning "Could not add any map points on any level - abort init", although I did translate the camera rather than rotate it. I changed the parameter "InitLevel: from 1 to 3, still not working.

**Comment by simonlynen** [comment]
This sounds like either your camera calibration is not accurate or too
little texture in the environment. How many trails do you see roughly
during the init?

**Comment by Ziyou1987** [comment]
I calibrated the camera again, and now it is working !  Thank you very much.

**Comment by iamfarhan007** [comment]
Hi im Using the sample bag file (ethzasl_ptam_desktop_sample;bag) on the http://wiki.ros.org/ethzasl_ptam/Tutorials/using_ethzasl_ptam
Whan i run the roslaunch ptam ptam.launch I Get the follwing message
CLEAR PARAMETERS
 * /ptam/

PARAMETERS
 * /ptam/ARBuffer_height
 * /ptam/ARBuffer_width
 * /ptam/AutoInitPixel
 * /ptam/BundleMEstimator
 * /ptam/Calibrator_BlurSigma
 * /ptam/Calibrator_MeanGate
 * /ptam/Calibrator_MinCornersForGrabbedImage
 * /ptam/Calibrator_NoDistortion
 * /ptam/Calibrator_Optimize
 * /ptam/Calibrator_Show
 * /ptam/Cam_cx
 * /ptam/Cam_cy
 * /ptam/Cam_fx
 * /ptam/Cam_fy
 * /ptam/Cam_s
 * /ptam/CameraCalibrator_CornerPatchSize
 * /ptam/CameraCalibrator_MaxStepDistFraction
 * /ptam/CandidateMinSTScore
 * /ptam/FASTMethod
 * /ptam/GLWindowMenu_Enable
 * /ptam/GLWindowMenu_mgvnMenuItemWidth
 * /ptam/GLWindowMenu_mgvnMenuTextOffset
 * /ptam/ImageSizeX
 * /ptam/ImageSizeY
 * /ptam/InitLevel
 * /ptam/MaxKF
 * /ptam/MaxKFDistWiggleMult
 * /ptam/MaxPatchesPerFrame
 * /ptam/MaxStereoInitLoops
 * /ptam/MinTukeySigma
 * /ptam/NoLevelZeroMapPoints
 * /ptam/TrackerMEstimator
 * /ptam/TrackingQualityFoundPixels
 * /ptam/UseKFPixelDist
 * /ptam/WiggleScale
 * /ptam/gui
 * /ptam/parent_frame
 * /rosdistro
 * /rosversion

NODES
  /
    ptam (ptam/ptam)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[ptam-1]: started with pid [15541]
[ INFO] [1427896285.184582970]: starting ptam with node name /ptam
  Welcome to PTAM 
  --------------- 
  Parallel tracking and mapping for Small AR workspaces
  Copyright (C) Isis Innovation Limited 2008 

Gui is on
[ptam-1] process has died [pid 15541, exit code -11, cmd /home/master/catkin_ws/devel/lib/ptam/ptam image:=/camera/image_raw pose:=pose __name:=ptam __log:=/home/master/.ros/log/cf52da6c-d873-11e4-a1ca-d8fc9361bda4/ptam-1.log].
log file: /home/master/.ros/log/cf52da6c-d873-11e4-a1ca-d8fc9361bda4/ptam-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done
can someone help please

**Comment by stephanweiss** [comment]
Hi

Just some sanity checks:
Did you load the correct camera parameters?
I assume you are on 14.04 and Indigo using the master branch of the package?

Best,
Stephan


________________________________

**Comment by iamfarhan007** [comment]
Thanks Stephan
i forgot to mention 
I using ubunto 12.04 and ROS groovy.
im using the same PtamFixParams.yml file which came along with ethzasl_ptam_desktop_sample.bag. i repleced it with the orignal one in /ethzasl_ptam/ptam 

best 
farhan

**Comment by stephanweiss** [comment]
I am not up to date on the status for 12.04 and groovy, but I think there might be a flag for it in the commit history. You could revert to that and test again. I doubt that the latest version on master will work flawlessly for 12.04 and groovy.
Also, did you have a look at the log files?

If your project allows to upgrade to 14.04 and fuerte, that might also solve some issues.

Best,
Stephan


________________________________

**Comment by iamfarhan007** [comment]
thanks
i will look into this matter . 
i getting another problem just by running the ptam node 



master@po-drone2:~/catkin_ws$ rosrun ptam ptam image:=/camera/image_raw
[ INFO] [1427921695.616893941]: starting ptam with node name /ptam
  Welcome to PTAM 
  --------------- 
  Parallel tracking and mapping for Small AR workspaces
  Copyright (C) Isis Innovation Limited 2008 

Gui is on
Segmentation fault

Perhaps it helps rectifying  the prolem


farhan

**Comment by stephanweiss** [comment]
Not quite sure what the root of this problem is.
Could you attach a log file with the output of "rosparam dump"?
I assume that you linked the topics correctly (verify with rqt_graph) and that the bag file is the only source providing the topic (i.e. no live sensors nor other bag files running).

Best
Stephan


________________________________

**Comment by iamfarhan007** [comment]
im relatively new to ROS , i dont get your first question ..........but  here r the log files in the  /home/master/.ros/log/cf52da6c-d873-11e4-a1ca-d8fc9361bda4/ folder 


I Ran the node again

 
master@po-drone2:~$ roslaunch ptam ptam.launch 
... logging to /home/master/.ros/log/a5de396a-d8b9-11e4-a1fe-d8fc9361bda4/roslaunch-po-drone2-9961.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://po-drone2:54471/

SUMMARY
========

CLEAR PARAMETERS
 * /ptam/

PARAMETERS
 * /ptam/ARBuffer_height
 * /ptam/ARBuffer_width
 * /ptam/AutoInitPixel
 * /ptam/BundleMEstimator
 * /ptam/Calibrator_BlurSigma
 * /ptam/Calibrator_MeanGate
 * /ptam/Calibrator_MinCornersForGrabbedImage
 * /ptam/Calibrator_NoDistortion
 * /ptam/Calibrator_Optimize
 * /ptam/Calibrator_Show
 * /ptam/Cam_cx
 * /ptam/Cam_cy
 * /ptam/Cam_fx
 * /ptam/Cam_fy
 * /ptam/Cam_s
 * /ptam/CameraCalibrator_CornerPatchSize
 * /ptam/CameraCalibrator_MaxStepDistFraction
 * /ptam/CandidateMinSTScore
 * /ptam/FASTMethod
 * /ptam/GLWindowMenu_Enable
 * /ptam/GLWindowMenu_mgvnMenuItemWidth
 * /ptam/GLWindowMenu_mgvnMenuTextOffset
 * /ptam/ImageSizeX
 * /ptam/ImageSizeY
 * /ptam/InitLevel
 * /ptam/MaxKF
 * /ptam/MaxKFDistWiggleMult
 * /ptam/MaxPatchesPerFrame
 * /ptam/MaxStereoInitLoops
 * /ptam/MinTukeySigma
 * /ptam/NoLevelZeroMapPoints
 * /ptam/TrackerMEstimator
 * /ptam/TrackingQualityFoundPixels
 * /ptam/UseKFPixelDist
 * /ptam/WiggleScale
 * /ptam/gui
 * /ptam/parent_frame
 * /rosdistro
 * /rosversion

NODES
  /
    ptam (ptam/ptam)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[ptam-1]: started with pid [9981]
[ INFO] [1427926837.974460085]: starting ptam with node name /ptam
  Welcome to PTAM 
  --------------- 
  Parallel tracking and mapping for Small AR workspaces
  Copyright (C) Isis Innovation Limited 2008 

Gui is on
[ptam-1] process has died [pid 9981, exit code -11, cmd /home/master/catkin_ws/devel/lib/ptam/ptam image:=/camera/image_raw pose:=pose __name:=ptam __log:=/home/master/.ros/log/a5de396a-d8b9-11e4-a1fe-d8fc9361bda4/ptam-1.log].
log file: /home/master/.ros/log/a5de396a-d8b9-11e4-a1fe-d8fc9361bda4/ptam-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done

$rqt_graph

![selection_003](https://cloud.githubusercontent.com/assets/10851317/6954053/38ab4832-d8ce-11e4-8f15-bb53b7320128.png)


thanks
farhan

**Comment by stephanweiss** [comment]
please do a
rosparam dump myparams.txt
and send me the myparams.txt file

**Comment by Ziyou1987** [comment]
Hi, iamfarhan007, have you solved your problem ? I was using my ASUS laptop with Ubuntu 12.04 and ROS groovy and having similar problems like yours. Then I upgraded the system to Ubuntu 14.04 and ROS indigo and the problem was gone. Also I run the PTAM on another older laptop with intel graphic card, still, the algorithm is running fine. You may try different computer or different OS and ROS.

**Comment by iamfarhan007** [comment]
i solved the problem yesterday . i removed groovy  with all its
dependencies and reinstalled it again
problem solved :-)

thanks
farhan

**Comment by stephanweiss** [comment]
Farhan,
Glad to hear things work now. Thanks very much for the update!

Best,
Stephan


________________________________

**Comment by iamfarhan007** [comment]
Hi everone
I again having probllem intailizing ethzasl_ptam . iv calibrated  my camera. im using image proc  node for pulishing image data on /camera3/image_mono . in the PtamFixParams.yaml iv set gui : true , imageSizeX: 752  
imageSizeY: 480
i got these values form camera3/camera_info

when i launch ptam ptam.launch

... logging to /home/asctec/.ros/log/034e189c-e510-11e4-a3a6-c4d9879214ea/roslaunch-mastermind-9745.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://mastermind:34641/

SUMMARY
========

CLEAR PARAMETERS
 * /ptam/

PARAMETERS
 * /ptam/ARBuffer_height
 * /ptam/ARBuffer_width
 * /ptam/AutoInitPixel
 * /ptam/BundleMEstimator
 * /ptam/Calibrator_BlurSigma
 * /ptam/Calibrator_MeanGate
 * /ptam/Calibrator_MinCornersForGrabbedImage
 * /ptam/Calibrator_NoDistortion
 * /ptam/Calibrator_Optimize
 * /ptam/Calibrator_Show
 * /ptam/Cam_cx
 * /ptam/Cam_cy
 * /ptam/Cam_fx
 * /ptam/Cam_fy
 * /ptam/Cam_s
 * /ptam/CameraCalibrator_CornerPatchSize
 * /ptam/CameraCalibrator_MaxStepDistFraction
 * /ptam/CandidateMinSTScore
 * /ptam/FASTMethod
 * /ptam/GLWindowMenu_Enable
 * /ptam/GLWindowMenu_mgvnMenuItemWidth
 * /ptam/GLWindowMenu_mgvnMenuTextOffset
 * /ptam/ImageSizeX
 * /ptam/ImageSizeY
 * /ptam/InitLevel
 * /ptam/MaxKF
 * /ptam/MaxKFDistWiggleMult
 * /ptam/MaxPatchesPerFrame
 * /ptam/MaxStereoInitLoops
 * /ptam/MinTukeySigma
 * /ptam/NoLevelZeroMapPoints
 * /ptam/TrackerMEstimator
 * /ptam/TrackingQualityFoundPixels
 * /ptam/UseKFPixelDist
 * /ptam/WiggleScale
 * /ptam/gui
 * /ptam/parent_frame
 * /rosdistro
 * /rosversion

NODES
  /
    ptam (ptam/ptam)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[ptam-1]: started with pid [9768]
[ INFO] [1429281848.716796560]: starting ptam with node name /ptam
  Welcome to PTAM 
  --------------- 
  Parallel tracking and mapping for Small AR workspaces
  Copyright (C) Isis Innovation Limited 2008 

Gui is on
[ptam-1] process has died [pid 9768, exit code -11, cmd /home/asctec/catkin_ws/devel/lib/ptam/ptam image:=/camera3/image_mono pose:=pose __name:=ptam __log:=/home/asctec/.ros/log/034e189c-e510-11e4-a3a6-c4d9879214ea/ptam-1.log].
log file: /home/asctec/.ros/log/034e189c-e510-11e4-a3a6-c4d9879214ea/ptam-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by stephanweiss** [comment]
Did you follow the suggestions of Farhan and Ziyou below?
Also, what is your OS and ROS version?

Best,
Stephan

________________________________

**Comment by iamfarhan007** [comment]
Hi stephan

now i installed ununto 14.04.1 ros indigo . but problem is i cannot build the package ethzasl_ptam
i get the following errors

.....................
Linking CXX executable /home/farhan/catkin_ws/devel/lib/ptam/ptam
/usr/bin/ld: cannot find -lblas
/usr/bin/ld: cannot find -llapack
collect2: error: ld returned 1 exit status
make[2]: *** [/home/farhan/catkin_ws/devel/lib/ptam/cameracalibrator] Error 1
make[1]: *** [ethzasl_ptam/ptam/CMakeFiles/cameracalibrator.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/bin/ld: cannot find -lblas
/usr/bin/ld: cannot find -llapack
collect2: error: ld returned 1 exit status
make[2]: *** [/home/farhan/catkin_ws/devel/lib/ptam/ptam] Error 1
make[1]: *** [ethzasl_ptam/ptam/CMakeFiles/ptam.dir/all] Error 2
make: *** [all] Error 2
Invoking "make -j4 -l4" failed

thanks
Farhan

**Comment by simonlynen** [comment]
@iamfarhan007 huh? Here https://github.com/ethz-asl/ethzasl_ptam/issues/59 you wrote that it is solved.

**Comment by iamfarhan007** [comment]
thanks simonlynen ... i forgot.... after reading #59 i managed to compile it
to stephan ... thanks for your advice iv now updated ubunto and ros to 14.04 and indigo
the ethzasl_ptam now just works fine for the sample bag file. on monday i will run it on my drone.

thanks  a lot
best
Farhan

**Comment by stephanweiss** [comment]
Gald to hear. So the take-home message for us is that we would need to do some work to get groovy + 12.04 running again with the sample data set. Not sure if and when that will happen, and if it is beneficial for the community. 

Best,
Stephan

**Comment by markusachtelik** [comment]
The ros groovy distro is officially not supported anymore, and with ros jade coming up soon, support for hydro will be stopped as well -- I'd rather focus efforts on getting this ready for jade, which I believe is more beneficial.
