### ISSUE TITLE
PTAM Installaltion problem

### ISSUE THREAD

**Issue by YadavKapil** [ethz-asl/ethzasl_ptam#56]
I could not install PTAM using the   instructions given in tutorial. I encounter error "catkin_make-command not found" when entering "catkin_make" in the terminal. I am following these instructions given in the official wiki of ptam - 
1. cd ~/catkin_ws/src
2. git clone https://github.com/ethz-asl/ethzasl_ptam
3. cd ..
4. catkin_make

I have catkin already installed.

**Comment by simonlynen** [comment]
This is not related to our package but to how you setup ROS (and catkin) itself. Please make sure that you have sourced the ROS environment:
```
source /opt/ros/indigo/setup.sh
```
if this does not resolve the problem, please refer to the ROS-answers web-page.
