### ISSUE TITLE
compilation problem ethzasl_ptam

### ISSUE THREAD

**Issue by iamfarhan007** [ethz-asl/ethzasl_ptam#59]
hello
im having the following compilation problem

Linking CXX executable /home/farhan/Desktop/catkin_ws/devel/lib/ptam/ptam
/usr/bin/ld: cannot find -lblas
/usr/bin/ld: cannot find -llapack
collect2: ld returned 1 exit status
make[2]: *** [/home/farhan/Desktop/catkin_ws/devel/lib/ptam/ptam] Error 1
make[1]: *** [ethzasl_ptam/ptam/CMakeFiles/ptam.dir/all] Error 2
make: *** [all] Error 2
Invoking "make" failed

regards

farhan

**Comment by simonlynen** [comment]
You need to install lapack and blas:
```
sudo apt-get install liblapack-dev libblas-dev
```

**Comment by iamfarhan007** [comment]
It solved the problem.. thanks a lot

farhan
