### ISSUE TITLE
compilation problem ethzasl_ptam

### ISSUE THREAD

**Issue by iamfarhan007** [ethz-asl/ethzasl_ptam#62]
Hi im having following probmem on ubunto 14.04 ROS indigo

Linking CXX executable /home/farhan/catkin_ws/devel/lib/ptam/ptam
/usr/bin/ld: cannot find -lglut
collect2: error: ld returned 1 exit status
make[2]: *** [/home/farhan/catkin_ws/devel/lib/ptam/cameracalibrator] Error 1
make[1]: *** [ethzasl_ptam/ptam/CMakeFiles/cameracalibrator.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/bin/ld: cannot find -lglut
collect2: error: ld returned 1 exit status
make[2]: *** [/home/farhan/catkin_ws/devel/lib/ptam/ptam] Error 1
make[1]: *** [ethzasl_ptam/ptam/CMakeFiles/ptam.dir/all] Error 2
make: *** [all] Error 2
Invoking "make -j4 -l4" failed

Thanks

Farhan

**Comment by iamfarhan007** [comment]
Hi 
i found the soultion 

 sudo apt-get install freeglut3-dev

thanks
Farhan

**Comment by simonlynen** [comment]
@iamfarhan007 please consider doing a quick google search before posting here. Thank you.
