### ISSUE TITLE
PTAM : libGL.so.1: error adding symbols: DSO missing from command line

### ISSUE THREAD

**Issue by 5aou** [ethz-asl/ethzasl_ptam#63]
Hi,I'm trying to install PTAM on ubuntu 14.04 and I have this error :

/usr/bin/ld: GLWindow2.o: référence au symbole non défini «glColorMask»
//usr/lib/x86_64-linux-gnu/mesa/libGL.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [PTAM] Erreur 1

Any suggestion please? And, thank you.

**Comment by simonlynen** [comment]
Closing in favor of https://github.com/ethz-asl/ethzasl_ptam/issues/48
