### ISSUE TITLE
PtamParamsConfig.h ..

### ISSUE THREAD

**Issue by unknownnn** [ethz-asl/ethzasl_ptam#72]
Hello,

I would like to use your library but it's not working in my computer, I'm using Ubuntu 14.04 and ROS Indigo. I've seen many topics about this issue (PtamParamsConfig.h missing.. ) but there is no real answer about this, I can't make it work .. I tried few tricks i have seen on topics but nothing work..

Thanks for your help

**Comment by simonlynen** [comment]
Can you please do the following and then post the full output of your terminal here:

```
cd ~/catkin_ws/build/ptam
make clean
make VERBOSE=1
```

**Comment by unknownnn** [comment]
Thank you for your quick answer :

cd /home/pierre/catkin_ws/build && /usr/bin/cmake -H/home/pierre/catkin_ws/src -B/home/pierre/catkin_ws/build --check-build-system CMakeFiles/Makefile.cmake 0
cd /home/pierre/catkin_ws/build && /usr/bin/cmake -E cmake_progress_start /home/pierre/catkin_ws/build/CMakeFiles /home/pierre/catkin_ws/build/ethzasl_ptam/ptam/CMakeFiles/progress.marks
cd /home/pierre/catkin_ws/build && make -f CMakeFiles/Makefile2 ethzasl_ptam/ptam/all
make[1]: entrant dans le répertoire « /home/pierre/catkin_ws/build »
make -f ethzasl_ptam/ptam/CMakeFiles/DEPS.dir/build.make ethzasl_ptam/ptam/CMakeFiles/DEPS.dir/depend
make[2]: entrant dans le répertoire « /home/pierre/catkin_ws/build »
cd /home/pierre/catkin_ws/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/pierre/catkin_ws/src /home/pierre/catkin_ws/src/ethzasl_ptam/ptam /home/pierre/catkin_ws/build /home/pierre/catkin_ws/build/ethzasl_ptam/ptam /home/pierre/catkin_ws/build/ethzasl_ptam/ptam/CMakeFiles/DEPS.dir/DependInfo.cmake --color=
make[2]: quittant le répertoire « /home/pierre/catkin_ws/build »
make -f ethzasl_ptam/ptam/CMakeFiles/DEPS.dir/build.make ethzasl_ptam/ptam/CMakeFiles/DEPS.dir/build
make[2]: entrant dans le répertoire « /home/pierre/catkin_ws/build »
cd /home/pierre/catkin_ws/build/ethzasl_ptam/ptam && echo Building all dependencies
Building all dependencies
cd /home/pierre/catkin_ws/build/ethzasl_ptam/ptam && cd /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty && make
make[3]: entrant dans le répertoire « /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty »
making third party libs
cd TooN && make
make[4]: entrant dans le répertoire « /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/TooN »
make[4]: Rien à faire pour « all ».
make[4]: quittant le répertoire « /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/TooN »
cd libcvd && make
make[4]: entrant dans le répertoire « /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/libcvd »
make[4]: Rien à faire pour « all ».
make[4]: quittant le répertoire « /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/libcvd »
cd gvars3 && make
make[4]: entrant dans le répertoire « /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/gvars3 »
make[4]: Rien à faire pour « all ».
make[4]: quittant le répertoire « /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/gvars3 »
cd agast && make
make[4]: entrant dans le répertoire « /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/agast »
mkdir -p bin
cd build && cmake -Wdev -DCMAKE_TOOLCHAIN_FILE=/opt/ros/indigo/share/ros/core/rosbuild/rostoolchain.cmake  ..
Re-run cmake no build system arguments
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/agast/build
cd build && make 
make[5]: entrant dans le répertoire « /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/agast/build »
/usr/bin/cmake -H/home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/agast -B/home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/agast/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/agast/build/CMakeFiles /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/agast/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[6]: entrant dans le répertoire « /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/agast/build »
make -f CMakeFiles/agast.dir/build.make CMakeFiles/agast.dir/depend
make[7]: entrant dans le répertoire « /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/agast/build »
cd /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/agast/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/agast /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/agast /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/agast/build /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/agast/build /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/agast/build/CMakeFiles/agast.dir/DependInfo.cmake --color=
make[7]: quittant le répertoire « /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/agast/build »
make -f CMakeFiles/agast.dir/build.make CMakeFiles/agast.dir/build
make[7]: entrant dans le répertoire « /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/agast/build »
make[7]: Rien à faire pour « CMakeFiles/agast.dir/build ».
make[7]: quittant le répertoire « /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/agast/build »
/usr/bin/cmake -E cmake_progress_report /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/agast/build/CMakeFiles  1 2 3 4 5 6 7 8 9 10
[100%] Built target agast
make[6]: quittant le répertoire « /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/agast/build »
/usr/bin/cmake -E cmake_progress_start /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/agast/build/CMakeFiles 0
make[5]: quittant le répertoire « /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/agast/build »
make[4]: quittant le répertoire « /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/agast »
make[3]: quittant le répertoire « /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty »
make[2]: quittant le répertoire « /home/pierre/catkin_ws/build »
/usr/bin/cmake -E cmake_progress_report /home/pierre/catkin_ws/build/CMakeFiles 
[  0%] Built target DEPS
make -f ethzasl_ptam/ptam/CMakeFiles/cameracalibrator.dir/build.make ethzasl_ptam/ptam/CMakeFiles/cameracalibrator.dir/depend
make[2]: entrant dans le répertoire « /home/pierre/catkin_ws/build »
cd /home/pierre/catkin_ws/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/pierre/catkin_ws/src /home/pierre/catkin_ws/src/ethzasl_ptam/ptam /home/pierre/catkin_ws/build /home/pierre/catkin_ws/build/ethzasl_ptam/ptam /home/pierre/catkin_ws/build/ethzasl_ptam/ptam/CMakeFiles/cameracalibrator.dir/DependInfo.cmake --color=
make[2]: quittant le répertoire « /home/pierre/catkin_ws/build »
make -f ethzasl_ptam/ptam/CMakeFiles/cameracalibrator.dir/build.make ethzasl_ptam/ptam/CMakeFiles/cameracalibrator.dir/build
make[2]: entrant dans le répertoire « /home/pierre/catkin_ws/build »
/usr/bin/cmake -E cmake_progress_report /home/pierre/catkin_ws/build/CMakeFiles 1
[  3%] Building CXX object ethzasl_ptam/ptam/CMakeFiles/cameracalibrator.dir/src/CameraCalibrator.cc.o
cd /home/pierre/catkin_ws/build/ethzasl_ptam/ptam && /usr/bin/c++   -DCVD_HAVE_TOON -DHAVE_GTK -DKF_REPROJ -DROSCONSOLE_BACKEND_LOG4CXX -DROS_BUILD_SHARED_LIBS=1 -DROS_PACKAGE_NAME=\"ptam\" -fsee -funsafe-loop-optimizations -fno-signed-zeros -fno-math-errno -funroll-loops -O3 -DNDEBUG -I/home/pierre/catkin_ws/devel/include -I/usr/include/opencv -I/home/pierre/catkin_ws/src/ethzasl_ptam/ptam/include -I/home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/TooN/include -I/home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/libcvd/include -I/home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/gvars3/include -I/home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/agast/include -I/opt/ros/indigo/include -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0 -I/usr/include/freetype2 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/libpng12 -I/usr/include/harfbuzz    -o CMakeFiles/cameracalibrator.dir/src/CameraCalibrator.cc.o -c /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/src/CameraCalibrator.cc
In file included from /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/src/CameraCalibrator.cc:5:0:
/home/pierre/catkin_ws/src/ethzasl_ptam/ptam/include/ptam/Params.h:11:35: fatal error: ptam/PtamParamsConfig.h: Aucun fichier ou dossier de ce type
 #include <ptam/PtamParamsConfig.h>
                                   ^
compilation terminated.
make[2]: **\* [ethzasl_ptam/ptam/CMakeFiles/cameracalibrator.dir/src/CameraCalibrator.cc.o] Erreur 1
make[2]: quittant le répertoire « /home/pierre/catkin_ws/build »
make[1]: **\* [ethzasl_ptam/ptam/CMakeFiles/cameracalibrator.dir/all] Erreur 2
make[1]: quittant le répertoire « /home/pierre/catkin_ws/build »
make: **\* [all] Erreur 2
pierre@pierre-VirtualBox:~/catkin_ws/build/ethzasl_ptam/ptam$

**Comment by simonlynen** [comment]
Can you comment the following lines and run the previous commands again, posting the output here:
https://github.com/ethz-asl/ethzasl_ptam/blob/master/ptam/CMakeLists.txt#L114-L151

**Comment by unknownnn** [comment]
cd /home/pierre/catkin_ws/build && /usr/bin/cmake -H/home/pierre/catkin_ws/src -B/home/pierre/catkin_ws/build --check-build-system CMakeFiles/Makefile.cmake 0
Re-run cmake file: Makefile older than: /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/CMakeLists.txt
-- Using CATKIN_DEVEL_PREFIX: /home/pierre/catkin_ws/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/indigo
-- This workspace overlays: /opt/ros/indigo
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/pierre/catkin_ws/build/test_results
-- Found gtest sources under '/usr/src/gtest': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.6.14
-- BUILD_SHARED_LIBS is on
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 8 packages in topological order:
-- ~~  - ethzasl_ptam (metapackage)
-- ~~  - ethzasl_sensor_fusion (metapackage)
-- ~~  - sensor_fusion_comm
-- ~~  - ptam_com
-- ~~  - rqt_ptam
-- ~~  - ssf_core
-- ~~  - ssf_updates
-- ~~  - ptam
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin metapackage: 'ethzasl_ptam'
-- ==> add_subdirectory(ethzasl_ptam/ethzasl_ptam)
-- +++ processing catkin metapackage: 'ethzasl_sensor_fusion'
-- ==> add_subdirectory(ethzasl_sensor_fusion/ethzasl_sensor_fusion)
-- +++ processing catkin package: 'sensor_fusion_comm'
-- ==> add_subdirectory(ethzasl_sensor_fusion/sensor_fusion_comm)
-- Using these message generators: gencpp;genlisp;genpy
-- sensor_fusion_comm: 3 messages, 0 services
-- +++ processing catkin package: 'ptam_com'
-- ==> add_subdirectory(ethzasl_ptam/ptam_com)
-- Using these message generators: gencpp;genlisp;genpy
-- ptam_com: 6 messages, 2 services
-- +++ processing catkin package: 'rqt_ptam'
-- ==> add_subdirectory(ethzasl_ptam/rqt_ptam)
-- +++ processing catkin package: 'ssf_core'
-- ==> add_subdirectory(ethzasl_sensor_fusion/ssf_core)
-- Eigen found (include: /usr/include/eigen3)
-- +++ processing catkin package: 'ssf_updates'
-- ==> add_subdirectory(ethzasl_sensor_fusion/ssf_updates)
-- Using these message generators: gencpp;genlisp;genpy
-- ssf_updates: 1 messages, 0 services
-- +++ processing catkin package: 'ptam'
-- ==> add_subdirectory(ethzasl_ptam/ptam)
-- Using these message generators: gencpp;genlisp;genpy
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pierre/catkin_ws/build
cd /home/pierre/catkin_ws/build && /usr/bin/cmake -E cmake_progress_start /home/pierre/catkin_ws/build/CMakeFiles /home/pierre/catkin_ws/build/ethzasl_ptam/ptam/CMakeFiles/progress.marks
cd /home/pierre/catkin_ws/build && make -f CMakeFiles/Makefile2 ethzasl_ptam/ptam/all
make[1]: entrant dans le répertoire « /home/pierre/catkin_ws/build »
make -f ethzasl_ptam/ptam/CMakeFiles/DEPS.dir/build.make ethzasl_ptam/ptam/CMakeFiles/DEPS.dir/depend
make[2]: entrant dans le répertoire « /home/pierre/catkin_ws/build »
cd /home/pierre/catkin_ws/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/pierre/catkin_ws/src /home/pierre/catkin_ws/src/ethzasl_ptam/ptam /home/pierre/catkin_ws/build /home/pierre/catkin_ws/build/ethzasl_ptam/ptam /home/pierre/catkin_ws/build/ethzasl_ptam/ptam/CMakeFiles/DEPS.dir/DependInfo.cmake --color=
Dependee "/home/pierre/catkin_ws/build/ethzasl_ptam/ptam/CMakeFiles/DEPS.dir/DependInfo.cmake" is newer than depender "/home/pierre/catkin_ws/build/ethzasl_ptam/ptam/CMakeFiles/DEPS.dir/depend.internal".
Scanning dependencies of target DEPS
make[2]: quittant le répertoire « /home/pierre/catkin_ws/build »
make -f ethzasl_ptam/ptam/CMakeFiles/DEPS.dir/build.make ethzasl_ptam/ptam/CMakeFiles/DEPS.dir/build
make[2]: entrant dans le répertoire « /home/pierre/catkin_ws/build »
cd /home/pierre/catkin_ws/build/ethzasl_ptam/ptam && echo Building all dependencies
Building all dependencies
cd /home/pierre/catkin_ws/build/ethzasl_ptam/ptam && cd /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty && make
make[3]: entrant dans le répertoire « /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty »
making third party libs
cd TooN && make
make[4]: entrant dans le répertoire « /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/TooN »
make[4]: Rien à faire pour « all ».
make[4]: quittant le répertoire « /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/TooN »
cd libcvd && make
make[4]: entrant dans le répertoire « /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/libcvd »
make[4]: Rien à faire pour « all ».
make[4]: quittant le répertoire « /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/libcvd »
cd gvars3 && make
make[4]: entrant dans le répertoire « /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/gvars3 »
make[4]: Rien à faire pour « all ».
make[4]: quittant le répertoire « /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/gvars3 »
cd agast && make
make[4]: entrant dans le répertoire « /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/agast »
mkdir -p bin
cd build && cmake -Wdev -DCMAKE_TOOLCHAIN_FILE=/opt/ros/indigo/share/ros/core/rosbuild/rostoolchain.cmake  ..
Re-run cmake no build system arguments
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/agast/build
cd build && make 
make[5]: entrant dans le répertoire « /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/agast/build »
/usr/bin/cmake -H/home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/agast -B/home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/agast/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/agast/build/CMakeFiles /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/agast/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[6]: entrant dans le répertoire « /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/agast/build »
make -f CMakeFiles/agast.dir/build.make CMakeFiles/agast.dir/depend
make[7]: entrant dans le répertoire « /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/agast/build »
cd /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/agast/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/agast /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/agast /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/agast/build /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/agast/build /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/agast/build/CMakeFiles/agast.dir/DependInfo.cmake --color=
make[7]: quittant le répertoire « /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/agast/build »
make -f CMakeFiles/agast.dir/build.make CMakeFiles/agast.dir/build
make[7]: entrant dans le répertoire « /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/agast/build »
make[7]: Rien à faire pour « CMakeFiles/agast.dir/build ».
make[7]: quittant le répertoire « /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/agast/build »
/usr/bin/cmake -E cmake_progress_report /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/agast/build/CMakeFiles  1 2 3 4 5 6 7 8 9 10
[100%] Built target agast
make[6]: quittant le répertoire « /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/agast/build »
/usr/bin/cmake -E cmake_progress_start /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/agast/build/CMakeFiles 0
make[5]: quittant le répertoire « /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/agast/build »
make[4]: quittant le répertoire « /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/agast »
make[3]: quittant le répertoire « /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/thirdparty »
make[2]: quittant le répertoire « /home/pierre/catkin_ws/build »
/usr/bin/cmake -E cmake_progress_report /home/pierre/catkin_ws/build/CMakeFiles 
[  0%] Built target DEPS
make -f ethzasl_ptam/ptam/CMakeFiles/ptam_gencfg.dir/build.make ethzasl_ptam/ptam/CMakeFiles/ptam_gencfg.dir/depend
make[2]: entrant dans le répertoire « /home/pierre/catkin_ws/build »
cd /home/pierre/catkin_ws/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/pierre/catkin_ws/src /home/pierre/catkin_ws/src/ethzasl_ptam/ptam /home/pierre/catkin_ws/build /home/pierre/catkin_ws/build/ethzasl_ptam/ptam /home/pierre/catkin_ws/build/ethzasl_ptam/ptam/CMakeFiles/ptam_gencfg.dir/DependInfo.cmake --color=
Dependee "/home/pierre/catkin_ws/build/ethzasl_ptam/ptam/CMakeFiles/ptam_gencfg.dir/DependInfo.cmake" is newer than depender "/home/pierre/catkin_ws/build/ethzasl_ptam/ptam/CMakeFiles/ptam_gencfg.dir/depend.internal".
Dependee "/home/pierre/catkin_ws/build/ethzasl_ptam/ptam/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/home/pierre/catkin_ws/build/ethzasl_ptam/ptam/CMakeFiles/ptam_gencfg.dir/depend.internal".
Scanning dependencies of target ptam_gencfg
make[2]: quittant le répertoire « /home/pierre/catkin_ws/build »
make -f ethzasl_ptam/ptam/CMakeFiles/ptam_gencfg.dir/build.make ethzasl_ptam/ptam/CMakeFiles/ptam_gencfg.dir/build
make[2]: entrant dans le répertoire « /home/pierre/catkin_ws/build »
/usr/bin/cmake -E cmake_progress_report /home/pierre/catkin_ws/build/CMakeFiles 33
[ 50%] Generating dynamic reconfigure files from cfg/PTAMVisualizerParams.cfg: /home/pierre/catkin_ws/devel/include/ptam/PTAMVisualizerParamsConfig.h /home/pierre/catkin_ws/devel/lib/python2.7/dist-packages/ptam/cfg/PTAMVisualizerParamsConfig.py
cd /home/pierre/catkin_ws/build/ethzasl_ptam/ptam && ../../catkin_generated/env_cached.sh /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/cfg/PTAMVisualizerParams.cfg /opt/ros/indigo/share/dynamic_reconfigure/cmake/.. /home/pierre/catkin_ws/devel/share/ptam /home/pierre/catkin_ws/devel/include/ptam /home/pierre/catkin_ws/devel/lib/python2.7/dist-packages/ptam
Generating reconfiguration files for PTAMVisualizerParams in ptam
Wrote header file in /home/pierre/catkin_ws/devel/include/ptam/PTAMVisualizerParamsConfig.h
/usr/bin/cmake -E cmake_progress_report /home/pierre/catkin_ws/build/CMakeFiles 34
[100%] Generating dynamic reconfigure files from cfg/PtamParams.cfg: /home/pierre/catkin_ws/devel/include/ptam/PtamParamsConfig.h /home/pierre/catkin_ws/devel/lib/python2.7/dist-packages/ptam/cfg/PtamParamsConfig.py
cd /home/pierre/catkin_ws/build/ethzasl_ptam/ptam && ../../catkin_generated/env_cached.sh /home/pierre/catkin_ws/src/ethzasl_ptam/ptam/cfg/PtamParams.cfg /opt/ros/indigo/share/dynamic_reconfigure/cmake/.. /home/pierre/catkin_ws/devel/share/ptam /home/pierre/catkin_ws/devel/include/ptam /home/pierre/catkin_ws/devel/lib/python2.7/dist-packages/ptam
Generating reconfiguration files for PtamParams in ptam
Wrote header file in /home/pierre/catkin_ws/devel/include/ptam/PtamParamsConfig.h
make[2]: quittant le répertoire « /home/pierre/catkin_ws/build »
/usr/bin/cmake -E cmake_progress_report /home/pierre/catkin_ws/build/CMakeFiles  33 34
[100%] Built target ptam_gencfg
make[1]: quittant le répertoire « /home/pierre/catkin_ws/build »
/usr/bin/cmake -E cmake_progress_start /home/pierre/catkin_ws/build/CMakeFiles 0

**Comment by simonlynen** [comment]
great, now it looks like the header was generated. Can you uncomment the executables in the CMakeLists.txt and run `cd ~/catkin_ws/build/ptam && make` (**don't run make clean**)

**Comment by unknownnn** [comment]
Ok perfect ! It's good, thanks a lot for your quick answer. You know from where the issue come ? And if there is a simplest way to solve it ? (I don't understand why the file is not generate on my computer automatically). 

Thanks again,

**Comment by simonlynen** [comment]
The dependencies between the targets are not setup correctly. The configuration files have not been processed by the time they are needed to build the executables. One would need to manually add a cmake-dependency between the targets.

**Comment by unknownnn** [comment]
Ok great Thank you

**Comment by enderless** [comment]
@simonlynen could you expand further on how to properly create a cmake-dependency between the targets? 

Your steps worked great otherwise.
