### ISSUE TITLE
the GUI display like this when calibrate the camera.

### ISSUE THREAD

**Issue by kintzhao** [ethz-asl/ethzasl_ptam#78]
![ptam2](https://cloud.githubusercontent.com/assets/11779271/11167798/f5315d3e-8bac-11e5-803b-62920b4d32d7.png)

roslaunch ptam cameracalibrator.launch 

when i run the camera node ,and display true in rviz ,but  when open the ptam calibrate ,display like the picture,why? can you tell me the reason , how to solve it ?

**Comment by notenti** [comment]
Did you figure out how to fix this issue? I am having the same problem and can't find a solution. Thanks.

**Comment by stephanweiss** [comment]
is it an rgb image?
what does rosrun image_view image_view image:=[your image topic] show?

**Comment by notenti** [comment]
It's a raw image; the camera is greyscale. If it helps I am using an mv bluefox camera. When I view the image in rviz is comes up perfectly.

**Comment by notenti** [comment]
Another thought: could it have to do with the TooN library? When I install TooN, libcvd, and gvars, the two latter libraries search for TooN, but can never find it in the system. I have tried setting all the paths manually, but ended up giving up. Could this be it?

**Comment by stephanweiss** [comment]
this could be the issue, try a clean checkout and compile using our repository.

**Comment by notenti** [comment]
I did a fresh install of TooN, libcvd, gvars, and PTAM and I'm still getting the double image. Could it have to do with my laptop's gpu?

**Comment by stephanweiss** [comment]
are you absolutely positive, that it is a b/w camera? Is your camera node converting it to a color image? I am fairly certain that this is a color/bw issue...or in general an issue how your image node is publishing the image and its meta info.

**Comment by notenti** [comment]
AH! It was.There was an option in the image publishing launch file where I could set whether to use color or not. Even though the camera was never publishing color images PTAM must have been treating it like it was. Thank you!

**Comment by stephanweiss** [comment]
Great! glad it was not another strange issue :-)
