### ISSUE TITLE
Getting a double image while Running camera Calibrator and ptam

### ISSUE THREAD

**Issue by siddyyagno3** [ethz-asl/ethzasl_ptam#81]
[screenshot from 2016-02-09 22 21 30](https://cloud.githubusercontent.com/assets/9764434/12923792/0e05a888-cf7d-11e5-813c-fcebe0b7f9c4.png)
While running Ptam and camera calibration we are getting a double image.
Our camera is logitech c270 [http://www.logitech.com/en-in/product/hd-webcam-c270](url)
We are publishing image using image publisher [http://wiki.ros.org/image_transport/Tutorials/PublishingImages](url).
Running camera calibrator using
`rosrun ptam cameracalibrator image:=/camera/image`.
Our ubuntu is 14.04.
Ros version is indigo.
open cv version 2.4.9
Thanks in advance for any help.

**Comment by vanurag** [comment]
Probably you are having similar issue as #76 You need to convert your color images to grayscale using image_proc

**Comment by siddyyagno3** [comment]
Thanx
yeah I fixed it by subscribing to image_mono
