### ISSUE TITLE
Moving away from the initialised ptam grid!

### ISSUE THREAD

**Issue by ank700** [ethz-asl/ethzasl_ptam#83]
Hi, ptam works fine on my pc if the initialised grid is in view. It is easy to keep the grid in view if the camera is facing forwards, but if it is facing downwards and I translate the camera such that the grid goes out of view, then after a few seconds, the tracking is lost (Attempting Recovery!). 

Is tracking possible even if the grid is not in view? I want to perform odometry for long distances (~500metres) inside/outside. 

Thanks

**Comment by stephanweiss** [comment]
Yes, tracking is possible even if the grid is not in view, in fact the grid is only for visualizing the area of origin and has nothing to do with the tracking or its quality. Most likely, your camera calibration is off. Please follow the tutorials on the ROS wiki to verify this.

Best,

Stephan

---

Von: ank700 notifications@github.com
Gesendet: Mittwoch, 01. Juni 2016 14:22
An: ethz-asl/ethzasl_ptam
Betreff: [ethz-asl/ethzasl_ptam] Moving away from the initialised ptam grid! (#83)

Hi, ptam works fine on my pc if the initialised grid is in view. It is easy to keep the grid in view if the camera is facing forwards, but if it is facing downwards and I translate the camera such that the grid goes out of view, then after a few seconds, the tracking is lost (Attempting Recovery!).

Is tracking possible even if the grid is not in view? I want to perform odometry for long distances (~500metres) inside/outside.

Thanks

##

**Comment by ank700** [comment]
Hello @stephanweiss , Thanks for your help. I calibrated the camera once again in careful light conditions. Now, it is much more stable. I was easily able to cover the whole lab with rotations and other crazy movements. Although, all movements have to be performed a little slowly otherwise it tries to attempt for recovery.

**Comment by stephanweiss** [comment]
great, glad to hear and thanks for the feedback.

Have fun with the framework!

---

Von: ank700 notifications@github.com
Gesendet: Freitag, 03. Juni 2016 17:57
An: ethz-asl/ethzasl_ptam
Cc: Stephan Weiss; Mention
Betreff: Re: [ethz-asl/ethzasl_ptam] Moving away from the initialised ptam grid! (#83)

Hello @stephanweisshttps://github.com/stephanweiss , Thanks for your help. I calibrated the camera once again in careful light conditions. Now, it is much more stable.

##
